version: "3.8"
services:
 # devpoc:
 #   build: .
 #   ports:
 #     - "8080:8080"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: devpocdb
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata
    ports:
      - "5432:5432"    